version: "3.1"

networks:
  api-networks:
    driver: bridge

services:

  node:
    build: 
      context: ./docker/node
    container_name: node
    working_dir: /backend
    volumes:
    - ./backend:/backend
    ports:
    - "5000:3000"
    command: bash -c "cd /backend && npm i && npm run start"
    networks: 
    - api-networks
    